version: "2"
use_cases:
- name: default
  sections:
  - name: terraform
    groups:
    - name: application
      technologies: [terraform]
      vars:
      - name: Environment
        description: The environment to filter resources by
        key: resource_env
        widget: dropdown
        type: string
        values: ["demo", "staging"]
      - name: "Virtual network"
        description: "Select multiple AWS VPC in which to deploy this environment sub network."
        key: resource_widget_example
        widget: cy_inventory_resource
        type: string
        required: true
        widget_config:
          attribute: id
          filters:
            environment: ${resource_env}

      - name: Team
        description: The team responsible for this environment
        key: team
        widget: dropdown
        type: string
        values_ref: https://robertparkin.github.io/data/teams.json
      - name: User
        description: The user responsible for this environment
        key: user
        widget: auto_complete
        type: string
        values_ref: https://robertparkin.github.io/data/users_${team}.json
        required: true
