---
# general-settings ADDITIONAL FORMS  #
use_cases:
- name: "default"  # the use_case is defined in the .cycloid.yml file
  sections:
  - name: "Virtual Machine"
    groups:
    - name: "Instance"
      technologies:
      - "pipeline"
      vars:
      - name: "public_subnets"
        description: "Public Subnets used by this chamber. For example: ['10.0.1.0/27',\
          \ '10.0.1.32/27']"
        key: "locals_public_subnets"
        type: "array"
        widget: "text_area"
        default:
        - "123"
        - "hello"
      - key: "message"
        widget: "simple_text"
        type: "string"
        name: "hello"
