version: 2
use_cases:
  - name: default
    sections:
      - name: ansible
        groups:
          - name: database
            technologies: [ ansible ]
            vars:
              - default: [[bar, foo]]
                description: multiselect array default
                key: one
                name: array default
                type: array
                unit: ($, GHz, GB)
                validations: null
                values: [[foo, bar], [bar, foo], [baz, qux]]
                widget: dropdown
                widget_config:
                  multiselect: true
              - default: [foo, bar ]
                widget: dropdown
                description: multiselect  non array default
                key: two
                name: non array default
                type: array
                unit: ($, GHz, GB)
                validations: null
                values: [foo, bar, baz, longtest, longtest1, another3, hey ]
                widget_config:
                  multiselect: true
