version: "2"
use_cases:
- name: default
  sections:
  - name: pipeline
    groups:
    - name: config
      technologies: [pipeline]
      vars:
      - name: "Message"
        description: "Message to display in the job"
        key: message
        widget: simple_text
        type: string
      - widget: dropdown
        type: string
        key: "interpolated_values_ref"
        name: "Inventory test"
        values_ref: "https://robertparkin.github.io/data/users_($ project_owner_canonical $).json"

