version: "2"
use_cases:
- name: default
  sections:
  - name: pipeline
    groups:
    - name: config
      technologies: [pipeline]
      vars:
      - name: "Message"
        description: "Message to display in the job"
        key: message
        widget: simple_text
        type: string
      - widget: dropdown
        type: string
        key: "interpolated_values_ref"
        name: "Inventory test"
        values_ref: "https://robertparkin.github.io/data/users_($ project_owner_name $).json"
      - widget: dropdown
        type: string
        key: "conditional_test"
        name: "Conditional test"
        values:
          options:
            - condition: "'($ project_owner_name $)' == 'admin'"
              values: ["8.0", "5.7"]
            - condition: "'($ project_owner_name $)' != 'admin'"
              values: ["13", "14", "15"]

