---
use_cases:
  - name: default
    sections:
      - name: Source base image
        groups:
          - name: Operating System
            technologies: [pipeline]
            vars:
              - name: Region
                key: region
                widget: auto_complete
                type: string
                default: "967d166"

              - name: VPC ID
                key: cycloid_vpc_id
                widget: dropdown
                type: map
                values_ref: https://pastefile.owl.cycloid.io/505c158da992cd3cd031278ab${region}
                required: true

              - name: Subnets to include in subnet group
                key: subnet_ids
                widget: dropdown
                required: true
                values_ref: https://pastefile.owl.cycloid.io/${cycloid_vpc_id}
                type: array
                widget_config:
                  multiselect: true